// window.client (obj)
// window.isExited  (bool, if is in game)
// window.username (string, user using the lobby)
// window.nowinBattle (int, which battle the user is in)
//window.displayedChat (int, which chat is being displayed)
//window.dbug (bool)
