// window.client (obj)
// window.ppl[usr]   returns teams 
// window.isExited  (bool, if is in prebattlezone)
// window.gameStatus  (bool, true means the game is in progress if the game is in progress)
// window.username (string, user using the lobby)
// window.nowinBattle (int, which battle the user is in)
//window.displayedChat (int, which chat is being displayed)
//window.dbug (bool)
//window.nowHostedby current btl hosted by which autohost
//window.roomPort[bid] returns the port of the room
//removeAllChildNodes(parents)  clears all child node
//window.isLoading bool, if is loading
//loading()
//window.isLoggedin bool if is logged in
//window.isLoggingin if is logging in 
//window.loadingCallback //call back func after a loading ends
//window.teamLeaders[teamLetter] //returns the user that's been designated as the leader
//window.zone="lobby" currently in what part of the lobby
//window.userVolume //1 to 100, an user set value that multiplies into window.audio.volume
//window.audio.volume //lobby volume
//storage // storage.set('unicorn', '🦄');console.log(storage.get('unicorn'));
//os //generated by os= require('os');
//fs //generated by fs = require('fs');
//process.env.WDIR  //working dir
//clearScreen(parentDiv)
// window.userNotifVolume
//window.userFXVolume
//window.isFxPlaying=false
