 const Store = require('electron-store');
 const fs = require('fs');
 window.runningEngineCount=0
 window.networkBuffer=""
 window.minimapCache={}
 window.specppl=[]
 window.ai={}
 window.mapDic=[]
 const storage=new Store();
 //const mapStorage=new Store();
 if (storage.has('userVolume')){
	 window.userVolume=storage.get('userVolume')}
	 else{
		 window.userVolume=50;
	 }
	 

if (storage.has('userFXVolume')){
	window.userFXVolume=storage.get('userFXVolume')}
else{
	window.userFXVolume=16;
	}

if (storage.has('userNotifVolume')){
	window.userNotifVolume=storage.get('userNotifVolume')}
else{
	window.userNotifVolume=16;
	}

	if (!storage.has('mapCache')||storage.get('mapCache')==undefined){
		//console.log('storage init ran!!!!!!!1')
		storage.set('mapCache',{'1':'2'})
		
		
	}
	
	if (typeof(process.env.WDIR)=='undefined'){
		process.env.WDIR=storage.get('wDIR')
	}
	else{
		
		storage.set('wDIR',process.env.WDIR)
	}
window.minimapCache={}
window.allMinimapCache=storage.get('mapCache')

window.chatUpdate={}
window.springSettings={
  "3DTrees": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/ITreeDrawer.cpp",
    "declarationLine": 26,
    "description": "Defines whether or not the trees generated by the engine (Default trees) will be shown as 3d or as cross sectioned ( + ) flat sides.",
    "defaultValue": 1,
    "safemodeValue": 0,
    "headlessValue": 0,
    "type": "bool"
  },
  "AdvMapShading": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 44,
    "description": "Enable shaders for terrain rendering.",
    "defaultValue": 1,
    "safemodeValue": 0,
    "type": "bool"
  },
  "AdvSky": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/ISky.cpp",
    "declarationLine": 18,
    "description": "Enables High Resolution Clouds.",
    "defaultValue": 0,
    "headlessValue": 0,
    "type": "bool"
  },
  "AdvUnitShading": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/UnitDrawer.cpp",
    "declarationLine": 61,
    "description": "Determines whether specular highlights and other lighting effects are rendered for units.",
    "defaultValue": 1,
    "safemodeValue": 0,
    "headlessValue": 0,
    "type": "bool"
  },
  "AllowDeferredMapRendering": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 45,
    "defaultValue": 0,
    "safemodeValue": 0,
    "type": "bool"
  },
  "AllowDeferredModelBufferClear": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 30,
    "defaultValue": 0,
    "safemodeValue": 0,
    "type": "bool"
  },
  "AllowDeferredModelRendering": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 29,
    "defaultValue": 0,
    "safemodeValue": 0,
    "type": "bool"
  },
  "AllowDrawMapPostDeferredEvents": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 46,
    "defaultValue": 1,
    "type": "bool"
  },
  "AllowDrawModelPostDeferredEvents": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 31,
    "defaultValue": 1,
    "type": "bool"
  },
  "AllowMultiSampledFrameBuffers": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 32,
    "defaultValue": 0,
    "type": "bool"
  },
  "AllowSpectatorJoin": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 73,
    "description": "allow any unauthenticated clients to join as spectator with any name, name will be prefixed with ~",
    "defaultValue": 1,
    "dedicatedValue": 0,
    "type": "bool"
  },
  "AtiHacks": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 40,
    "description": "Enables graphics drivers workarounds for users with ATI video cards.\n -1:=runtime detect, 0:=off, 1:=on",
    "defaultValue": -1,
    "minimumValue": -1,
    "maximumValue": 1,
    "headlessValue": 0,
    "type": "int"
  },
  "AtiSwapRBFix": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GL/FBO.cpp",
    "declarationLine": 16,
    "defaultValue": 0,
    "type": "bool"
  },
  "AutoAddBuiltUnitsToFactoryGroup": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/SelectedUnitsHandler.cpp",
    "declarationLine": 49,
    "description": "Controls whether or not units built by factories will inherit that factory's unit group.",
    "defaultValue": 0,
    "type": "bool"
  },
  "AutoAddBuiltUnitsToSelectedGroup": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/SelectedUnitsHandler.cpp",
    "declarationLine": 50,
    "defaultValue": 0,
    "type": "bool"
  },
  "AutohostIP": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 78,
    "defaultValue": "127.0.0.1",
    "type": "std::string"
  },
  "AutohostPort": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 69,
    "defaultValue": 0,
    "type": "int"
  },
  "BlockCompositing": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 52,
    "description": "Disables kwin compositing to fix tearing, possible fixes low FPS in windowed mode, too.",
    "defaultValue": 0,
    "safemodeValue": 1,
    "type": "bool"
  },
  "BuildIconsFirst": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/SelectedUnitsHandler.cpp",
    "declarationLine": 48,
    "defaultValue": 0,
    "type": "bool"
  },
  "BumpWaterAnisotropy": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 47,
    "defaultValue": 0,
    "minimumValue": 0,
    "type": "float"
  },
  "BumpWaterBlurReflection": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 50,
    "defaultValue": 0,
    "type": "bool"
  },
  "BumpWaterDepthBits": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 49,
    "defaultValue": 24,
    "minimumValue": 16,
    "maximumValue": 32,
    "type": "int"
  },
  "BumpWaterDynamicWaves": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 53,
    "defaultValue": 1,
    "type": "bool"
  },
  "BumpWaterEndlessOcean": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 52,
    "description": "Sets whether Bumpmapped water will be drawn beyond the map edge.",
    "defaultValue": 1,
    "type": "bool"
  },
  "BumpWaterOcclusionQuery": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 55,
    "defaultValue": 0,
    "type": "bool"
  },
  "BumpWaterReflection": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 45,
    "description": "Determines the amount of objects reflected in Bumpmapped water.\n0:=off, 1:=fast (skip terrain), 2:=full",
    "defaultValue": 1,
    "minimumValue": 0,
    "maximumValue": 2,
    "headlessValue": 0,
    "type": "int"
  },
  "BumpWaterRefraction": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 46,
    "description": "Determines the method of refraction with Bumpmapped water.\n0:=off, 1:=screencopy, 2:=own rendering cycle (disabled)",
    "defaultValue": 1,
    "minimumValue": 0,
    "maximumValue": 1,
    "headlessValue": 0,
    "type": "int"
  },
  "BumpWaterShoreWaves": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 51,
    "description": "Enables rendering of shorewaves.",
    "defaultValue": 1,
    "safemodeValue": 0,
    "headlessValue": 0,
    "type": "bool"
  },
  "BumpWaterTexSizeReflection": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 44,
    "description": "Sets the size of the framebuffer texture used to store the reflection in Bumpmapped water.",
    "defaultValue": 512,
    "minimumValue": 32,
    "headlessValue": 32,
    "type": "int"
  },
  "BumpWaterUseDepthTexture": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 48,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "BumpWaterUseUniforms": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BumpWater.cpp",
    "declarationLine": 54,
    "defaultValue": 0,
    "type": "bool"
  },
  "CamFreeAngVelTime": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 29,
    "defaultValue": 1,
    "type": "float"
  },
  "CamFreeAutoTilt": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 27,
    "description": "When free camera is locked, AutoTilt will point the camera in the direction of the ground's slope",
    "defaultValue": 150,
    "type": "float"
  },
  "CamFreeEnabled": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 18,
    "defaultValue": 0,
    "type": "bool"
  },
  "CamFreeFOV": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 21,
    "defaultValue": 45,
    "type": "float"
  },
  "CamFreeGoForward": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 20,
    "defaultValue": 0,
    "type": "bool"
  },
  "CamFreeGravity": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 23,
    "description": "When free camera is locked, Gravity will be used if you jump off of a ground ramp.",
    "defaultValue": -500,
    "type": "float"
  },
  "CamFreeGroundOffset": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 25,
    "description": "Determines ground handling for the free camera.\n0 - the camera can move anywhere,\n< 0 - the camera is always offset from the ground height by -CamFreeGroundOffset\n> 0 - the camera can be \"locked\" to the ground by using SHIFT UP_ARROW. (and will use CamFreeGroundOffset as the offset). To release the lock, simply press SHIFT DOWN_ARROW.",
    "defaultValue": 16,
    "type": "float"
  },
  "CamFreeInvertAlt": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 19,
    "defaultValue": 0,
    "type": "bool"
  },
  "CamFreeScrollSpeed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 22,
    "defaultValue": 500,
    "type": "float"
  },
  "CamFreeSlide": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 24,
    "defaultValue": 0.5,
    "type": "float"
  },
  "CamFreeTiltSpeed": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 26,
    "defaultValue": 150,
    "type": "float"
  },
  "CamFreeVelTime": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FreeController.cpp",
    "declarationLine": 28,
    "defaultValue": 1.5,
    "type": "float"
  },
  "CamMode": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/CameraHandler.cpp",
    "declarationLine": 41,
    "description": "Defines the used camera. Options are:\n0 = FPS\n1 = Overhead\n2 = Spring\n3 = RotOverhead\n4 = Free\n5 = Overview",
    "defaultValue": 2,
    "minimumValue": 0,
    "maximumValue": 5,
    "type": "int"
  },
  "CamModeName": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/CameraHandler.cpp",
    "declarationLine": 39,
    "defaultValue": "",
    "type": "std::string"
  },
  "CamSpringEdgeRotate": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 24,
    "description": "Rotate camera when cursor touches screen borders.",
    "defaultValue": 0,
    "type": "bool"
  },
  "CamSpringEnabled": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 18,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "CamSpringFOV": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 20,
    "defaultValue": 45,
    "type": "float"
  },
  "CamSpringLockCardinalDirections": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 21,
    "description": "Whether cardinal directions should be `locked` for a short time when rotating.",
    "defaultValue": 1,
    "type": "bool"
  },
  "CamSpringScrollSpeed": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 19,
    "defaultValue": 10,
    "type": "int"
  },
  "CamSpringZoomInToMousePos": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 22,
    "defaultValue": 1,
    "type": "bool"
  },
  "CamSpringZoomOutFromMousePos": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/SpringController.cpp",
    "declarationLine": 23,
    "defaultValue": 0,
    "type": "bool"
  },
  "CamTimeExponent": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/CameraHandler.cpp",
    "declarationLine": 59,
    "description": "Camera transitions happen at lerp(old, new, timeNorm ^ CamTimeExponent).",
    "defaultValue": 4,
    "minimumValue": 0,
    "type": "float"
  },
  "CamTimeFactor": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/CameraHandler.cpp",
    "declarationLine": 54,
    "description": "Scales the speed of camera transitions, e.g. zooming or position change.",
    "defaultValue": 1,
    "minimumValue": 0,
    "type": "float"
  },
  "ColorElev": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/HeightLinePalette.cpp",
    "declarationLine": 8,
    "description": "If heightmap (default hotkey [F1]) should be colored or not.",
    "defaultValue": 1,
    "type": "bool"
  },
  "CompressTextures": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 43,
    "description": "Runtime compress most textures to save VideoRAM.",
    "defaultValue": 0,
    "safemodeValue": 1,
    "type": "bool"
  },
  "CrossAlpha": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 59,
    "defaultValue": 0.5,
    "type": "float"
  },
  "CrossMoveScale": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 60,
    "defaultValue": 1,
    "type": "float"
  },
  "CrossSize": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 58,
    "defaultValue": 12,
    "type": "float"
  },
  "CubeTexGenerateMipMaps": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/CubeMapHandler.cpp",
    "declarationLine": 20,
    "defaultValue": 0,
    "type": "bool"
  },
  "CubeTexSizeReflection": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/CubeMapHandler.cpp",
    "declarationLine": 19,
    "defaultValue": 128,
    "minimumValue": 1,
    "type": "int"
  },
  "CubeTexSizeSpecular": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/CubeMapHandler.cpp",
    "declarationLine": 18,
    "defaultValue": 128,
    "minimumValue": 1,
    "type": "int"
  },
  "DebugGL": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 29,
    "description": "Enables GL debug-context and output. (see GL_ARB_debug_output)",
    "defaultValue": 0,
    "type": "bool"
  },
  "DebugGLStacktraces": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 30,
    "description": "Create a stacktrace when an OpenGL error occurs",
    "defaultValue": 0,
    "type": "bool"
  },
  "DefaultLuaMenu": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/LuaMenuController.cpp",
    "declarationLine": 16,
    "description": "Sets the default menu to be used when spring is started.",
    "defaultValue": "",
    "type": "std::string"
  },
  "DefaultStartScript": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 106,
    "description": "filename of script.txt to use when no command line parameters are specified.",
    "defaultValue": "",
    "type": "std::string"
  },
  "DemoFromDemo": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/PreGame.cpp",
    "declarationLine": 61,
    "defaultValue": 0,
    "type": "bool"
  },
  "DisableDemoVersionCheck": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/LoadSave/DemoReader.cpp",
    "declarationLine": 10,
    "description": "Allow to play every replay file (may crash / cause undefined behaviour in replays)",
    "defaultValue": 0,
    "type": "bool"
  },
  "DoubleClickTime": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 62,
    "description": "Double click time in milliseconds.",
    "defaultValue": 200,
    "type": "float"
  },
  "DualScreenMiniMapOnLeft": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 45,
    "description": "When set, will make the left half of the screen the minimap when DualScreenMode is set.",
    "defaultValue": 0,
    "type": "bool"
  },
  "DualScreenMode": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 44,
    "description": "Sets whether to split the screen in half, with one half for minimap and one for main screen. Right side is for minimap unless DualScreenMiniMapOnLeft is set.",
    "defaultValue": 0,
    "type": "bool"
  },
  "DynamicSky": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/BasicSky.cpp",
    "declarationLine": 23,
    "description": "Sets whether the clouds in the sky will be procedurally generated and moved. Resource heavy!",
    "defaultValue": 0,
    "type": "bool"
  },
  "EdgeMoveDynamic": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera.cpp",
    "declarationLine": 22,
    "description": "If EdgeMove scrolling speed should fade with edge distance.",
    "defaultValue": 1,
    "type": "bool"
  },
  "EdgeMoveWidth": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera.cpp",
    "declarationLine": 18,
    "description": "The width (in percent of screen size) of the EdgeMove scrolling area.",
    "defaultValue": 0.02,
    "minimumValue": 0,
    "type": "float"
  },
  "ExtraTextureUpdateRate": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Map/InfoTexture/Legacy/LegacyInfoTextureHandler.cpp",
    "declarationLine": 22,
    "description": "EXTREME CPU-HEAVY ON MEDIUM/BIG MAPS! DON'T CHANGE DEFAULT!",
    "defaultValue": 45,
    "type": "int"
  },
  "FPSClampPos": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FPSController.cpp",
    "declarationLine": 18,
    "defaultValue": 1,
    "type": "bool"
  },
  "FPSEnabled": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FPSController.cpp",
    "declarationLine": 16,
    "defaultValue": 1,
    "type": "bool"
  },
  "FPSFOV": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/FPSController.cpp",
    "declarationLine": 17,
    "defaultValue": 45,
    "type": "float"
  },
  "FPSMouseScale": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/FPSController.cpp",
    "declarationLine": 15,
    "defaultValue": 0.01,
    "type": "float"
  },
  "FPSScrollSpeed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/FPSController.cpp",
    "declarationLine": 14,
    "defaultValue": 10,
    "type": "int"
  },
  "FeatureDrawDistance": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/FeatureDrawer.cpp",
    "declarationLine": 40,
    "description": "Maximum distance at which features will be drawn.",
    "defaultValue": 6000,
    "minimumValue": 0,
    "type": "float"
  },
  "FeatureFadeDistance": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/FeatureDrawer.cpp",
    "declarationLine": 45,
    "description": "Distance at which features will begin to fade from view.",
    "defaultValue": 4500,
    "minimumValue": 0,
    "type": "float"
  },
  "FontFile": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 23,
    "description": "Sets the font of Spring engine text.",
    "defaultValue": "fonts/FreeSansBold.otf",
    "type": "std::string"
  },
  "FontOutlineWeight": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 30,
    "description": "Sets the opacity of Spring engine text, such as the title screen version number, clock, and basic UI. Does not affect LuaUI elements.",
    "defaultValue": 25,
    "type": "float"
  },
  "FontOutlineWidth": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 28,
    "description": "Sets the width of the black outline around Spring engine text, such as the title screen version number, clock, and basic UI. Does not affect LuaUI elements.",
    "defaultValue": 3,
    "type": "int"
  },
  "FontSize": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 26,
    "description": "Sets the font size (in pixels) of the MainMenu and more.",
    "defaultValue": 23,
    "type": "int"
  },
  "ForceCoreContext": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 38,
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 1,
    "type": "int"
  },
  "ForceDisableClipCtrl": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 37,
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 1,
    "type": "int"
  },
  "ForceDisableShaders": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 36,
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 1,
    "type": "int"
  },
  "ForceSwapBuffers": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 39,
    "defaultValue": 1,
    "minimumValue": 0,
    "maximumValue": 1,
    "type": "int"
  },
  "Fullscreen": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 50,
    "description": "Sets whether the game will run in fullscreen, as opposed to a window. For Windowed Fullscreen of Borderless Window, set this to 0, WindowBorderless to 1, and WindowPosX and WindowPosY to 0.",
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "FullscreenEdgeMove": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 131,
    "description": "see WindowedEdgeMove, just for fullscreen mode",
    "defaultValue": 1,
    "type": "bool"
  },
  "GLContextMajorVersion": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 32,
    "defaultValue": 3,
    "minimumValue": 3,
    "maximumValue": 4,
    "type": "int"
  },
  "GLContextMinorVersion": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 33,
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 5,
    "type": "int"
  },
  "GameEndOnConnectionLoss": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 127,
    "defaultValue": 1,
    "type": "bool"
  },
  "GrassDetail": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/GrassDrawer.cpp",
    "declarationLine": 35,
    "description": "Sets how detailed the engine rendered grass will be on any given map.",
    "defaultValue": 7,
    "minimumValue": 0,
    "headlessValue": 0,
    "type": "int"
  },
  "GroundDecals": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/IGroundDecalDrawer.cpp",
    "declarationLine": 12,
    "description": "Controls whether ground decals underneath buildings and ground scars from explosions will be rendered. Values >1 define how long such decals will stay.",
    "defaultValue": 3,
    "headlessValue": 0,
    "type": "int"
  },
  "GroundDecalsParallaxMapping": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/Decals/DecalsDrawerGL4.cpp",
    "declarationLine": 46,
    "defaultValue": 1,
    "type": "bool"
  },
  "GroundDetail": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 31,
    "description": "Controls how detailed the map geometry will be. On lowered settings, cliffs may appear to be jagged or \"melting\".",
    "defaultValue": 60,
    "minimumValue": 4,
    "maximumValue": 200,
    "headlessValue": 0,
    "type": "int"
  },
  "GroundLODScaleReflection": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/BaseGroundDrawer.cpp",
    "declarationLine": 7,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "float"
  },
  "GroundLODScaleRefraction": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/BaseGroundDrawer.cpp",
    "declarationLine": 8,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "float"
  },
  "GroundLODScaleTerrainReflection": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/BaseGroundDrawer.cpp",
    "declarationLine": 9,
    "defaultValue": 1,
    "type": "float"
  },
  "GroundNormalTextureHighPrecision": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFReadMap.cpp",
    "declarationLine": 34,
    "defaultValue": 0,
    "type": "bool"
  },
  "GroundScarAlphaFade": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Env/Decals/GroundDecalHandler.cpp",
    "declarationLine": 55,
    "defaultValue": 0,
    "type": "int"
  },
  "GuiOpacity": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 137,
    "description": "Sets the opacity of the built-in Spring UI. Generally has no effect on LuaUI widgets. Can be set in-game using shift+, to decrease and shift+. to increase.",
    "defaultValue": 0.8,
    "minimumValue": 0,
    "maximumValue": 1,
    "type": "float"
  },
  "HangTimeout": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/Platform/Watchdog.cpp",
    "declarationLine": 24,
    "description": "Number of seconds that, if spent in the same code segment, indicate a hang; -1 to disable.",
    "defaultValue": 10,
    "minimumValue": -1,
    "maximumValue": 600,
    "type": "int"
  },
  "HardwareCursor": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 54,
    "description": "Sets hardware mouse cursor rendering. If you have a low framerate, your mouse cursor will seem \"laggy\". Setting hardware cursor will render the mouse cursor separately from spring and the mouse will behave normally. Note, not all GPU drivers support it in fullscreen mode!",
    "defaultValue": 0,
    "type": "bool"
  },
  "HighResInfoTexture": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Map/InfoTexture/Modern/Combiner.cpp",
    "declarationLine": 14,
    "defaultValue": 1,
    "type": "bool"
  },
  "HighResLos": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Map/InfoTexture/Legacy/LegacyInfoTextureHandler.cpp",
    "declarationLine": 21,
    "description": "Controls whether LOS (\"L view\") edges are rendered in high resolution. Resource heavy!",
    "defaultValue": 0,
    "type": "bool"
  },
  "HostIPDefault": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/ClientSetup.cpp",
    "declarationLine": 16,
    "description": "Default IP to use for hosting if not specified in script.txt",
    "defaultValue": "localhost",
    "dedicatedValue": "",
    "type": "std::string"
  },
  "HostPortDefault": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/ClientSetup.cpp",
    "declarationLine": 17,
    "description": "Default Port to use for hosting if not specified in script.txt",
    "defaultValue": 8452,
    "minimumValue": 0,
    "maximumValue": 65535,
    "type": "int"
  },
  "InfoConsoleGeometry": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/InfoConsole.cpp",
    "declarationLine": 14,
    "defaultValue": "0.26 0.96 0.41 0.205",
    "type": "std::string"
  },
  "InfoMessageTime": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/InfoConsole.cpp",
    "declarationLine": 13,
    "description": "Time until old messages disappear from the ingame console.",
    "defaultValue": 10,
    "type": "int"
  },
  "InitialNetworkTimeout": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 15,
    "defaultValue": 30,
    "minimumValue": 10,
    "type": "int"
  },
  "InputTextGeo": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 138,
    "defaultValue": "",
    "type": "std::string"
  },
  "InvertMouse": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 55,
    "defaultValue": 0,
    "type": "bool"
  },
  "InvertQueueKey": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/GuiHandler.cpp",
    "declarationLine": 60,
    "defaultValue": 0,
    "type": "bool"
  },
  "KeyChainTimeout": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/KeyBindings.cpp",
    "declarationLine": 27,
    "description": "Timeout in milliseconds waiting for a key chain shortcut.",
    "defaultValue": 750,
    "minimumValue": 0,
    "type": "int"
  },
  "LODScale": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 34,
    "defaultValue": 1,
    "type": "float"
  },
  "LODScaleReflection": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 36,
    "defaultValue": 1,
    "type": "float"
  },
  "LODScaleRefraction": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 37,
    "defaultValue": 1,
    "type": "float"
  },
  "LODScaleShadow": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/LuaObjectDrawer.cpp",
    "declarationLine": 35,
    "defaultValue": 1,
    "type": "float"
  },
  "LastSelectedMap": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/SelectionWidget.cpp",
    "declarationLine": 27,
    "description": "Stores the previously played map.",
    "defaultValue": "No map selected",
    "type": "std::string"
  },
  "LastSelectedMod": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/SelectionWidget.cpp",
    "declarationLine": 26,
    "description": "Stores the previously played game.",
    "defaultValue": "No game selected",
    "type": "std::string"
  },
  "LastSelectedScript": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/SelectionWidget.cpp",
    "declarationLine": 28,
    "description": "Stores the previously played AI.",
    "defaultValue": "No script selected",
    "type": "std::string"
  },
  "LastSelectedSetting": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/SelectMenu.cpp",
    "declarationLine": 45,
    "description": "Stores the previously selected setting, when editing settings within the Spring main menu.",
    "defaultValue": "",
    "type": "std::string"
  },
  "LinkIncomingMaxPacketRate": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 43,
    "defaultValue": 64,
    "minimumValue": 0,
    "type": "int"
  },
  "LinkIncomingMaxWaitingPackets": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 49,
    "defaultValue": 512,
    "minimumValue": 0,
    "type": "int"
  },
  "LinkIncomingPeakBandwidth": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 39,
    "defaultValue": 32768,
    "minimumValue": 0,
    "type": "int"
  },
  "LinkIncomingSustainedBandwidth": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 35,
    "defaultValue": 2048,
    "minimumValue": 0,
    "type": "int"
  },
  "LinkOutgoingBandwidth": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 31,
    "defaultValue": 65536,
    "minimumValue": 0,
    "type": "int"
  },
  "LoadingMT": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/LoadScreen.cpp",
    "declarationLine": 42,
    "defaultValue": 0,
    "safemodeValue": 0,
    "type": "int"
  },
  "LogClientData": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/NetCommands.cpp",
    "declarationLine": 40,
    "defaultValue": 0,
    "type": "bool"
  },
  "LogFlushLevel": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/LogOutput.cpp",
    "declarationLine": 38,
    "description": "Flush the logfile when a message's level exceeds this value. ERROR is flushed by default, WARNING is not.",
    "defaultValue": 50,
    "type": "int"
  },
  "LogRepeatLimit": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/LogOutput.cpp",
    "declarationLine": 42,
    "description": "Allow at most this many consecutive identical messages to be logged.",
    "defaultValue": 10,
    "type": "int"
  },
  "LogSections": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/LogOutput.cpp",
    "declarationLine": 33,
    "description": "Comma-separated list of enabled logsections, see infolog.txt / console output for possible values.",
    "defaultValue": "",
    "type": "std::string"
  },
  "LuaGarbageCollectionMemLoadMult": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Lua/LuaHandle.cpp",
    "declarationLine": 55,
    "defaultValue": 1.33,
    "minimumValue": 1,
    "maximumValue": 100,
    "type": "float"
  },
  "LuaGarbageCollectionRunTimeMult": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Lua/LuaHandle.cpp",
    "declarationLine": 56,
    "description": "in milliseconds",
    "defaultValue": 5,
    "minimumValue": 1,
    "type": "float"
  },
  "LuaShaders": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Lua/LuaOpenGL.cpp",
    "declarationLine": 76,
    "defaultValue": 1,
    "safemodeValue": 0,
    "headlessValue": 0,
    "type": "bool"
  },
  "LuaSocketEnabled": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Lua/LuaUI.cpp",
    "declarationLine": 47,
    "description": "Enable LuaSocket support, allows Lua widgets to make TCP/UDP connections",
    "readOnly": 1,
    "defaultValue": 1,
    "type": "bool"
  },
  "LuaWritableConfigFile": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 60,
    "defaultValue": 1,
    "type": "bool"
  },
  "MSAALevel": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 34,
    "description": "Enables multisample anti-aliasing; 'level' is the number of samples used.",
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 32,
    "type": "int"
  },
  "MapBorder": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 37,
    "description": "Draws a solid border at the edges of the map.",
    "defaultValue": 1,
    "type": "bool"
  },
  "MaxDynamicMapLights": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 40,
    "defaultValue": 1,
    "minimumValue": 0,
    "type": "int"
  },
  "MaxDynamicModelLights": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/UnitDrawer.cpp",
    "declarationLine": 57,
    "defaultValue": 1,
    "minimumValue": 0,
    "type": "int"
  },
  "MaxNanoParticles": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Sim/Projectiles/ProjectileHandler.cpp",
    "declarationLine": 41,
    "defaultValue": 2000,
    "minimumValue": 0,
    "headlessValue": 0,
    "type": "int"
  },
  "MaxParticles": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Sim/Projectiles/ProjectileHandler.cpp",
    "declarationLine": 40,
    "defaultValue": 10000,
    "minimumValue": 0,
    "headlessValue": 0,
    "type": "int"
  },
  "MaxPathCostsMemoryFootPrint": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Sim/Path/Default/PathEstimator.cpp",
    "declarationLine": 36,
    "description": "Maximum memusage (in MByte) of multithreaded pathcache generator at loading time.",
    "defaultValue": 512,
    "minimumValue": 64,
    "type": "int"
  },
  "MaxSounds": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 28,
    "description": "Maximum sounds played in parallel.",
    "defaultValue": 128,
    "minimumValue": 1,
    "headlessValue": 1,
    "type": "int"
  },
  "MaximumTransmissionUnit": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 27,
    "defaultValue": 1400,
    "minimumValue": 400,
    "type": "int"
  },
  "MenuArchive": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/SelectMenu.cpp",
    "declarationLine": 46,
    "description": "Archive name for the default Menu.",
    "defaultValue": "Spring Bitmaps",
    "type": "std::string"
  },
  "MiddleClickScrollSpeed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/OverheadController.cpp",
    "declarationLine": 18,
    "defaultValue": 0.01,
    "type": "float"
  },
  "MiniMapButtonSize": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 48,
    "defaultValue": 16,
    "type": "int"
  },
  "MiniMapCursorScale": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 55,
    "defaultValue": -0.5,
    "type": "float"
  },
  "MiniMapDrawCommands": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 58,
    "defaultValue": 1,
    "minimumValue": 0,
    "headlessValue": 0,
    "type": "int"
  },
  "MiniMapDrawProjectiles": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 60,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "MiniMapFullProxy": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 47,
    "defaultValue": 1,
    "type": "bool"
  },
  "MiniMapGeometry": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 46,
    "defaultValue": "2 2 200 200",
    "type": "std::string"
  },
  "MiniMapIcons": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 56,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "MiniMapMarker": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/UI/GuiHandler.cpp",
    "declarationLine": 59,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "MiniMapRefreshRate": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 64,
    "description": "The refresh rate of the async MiniMap texture. Needs MiniMapRenderToTexture to be true. Value of \"0\" autoselects between 10-60FPS.",
    "defaultValue": 0,
    "minimumValue": 0,
    "type": "int"
  },
  "MiniMapRenderToTexture": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 63,
    "description": "Asynchronous render MiniMap to a texture independent of screen FPS.",
    "defaultValue": 1,
    "safemodeValue": 0,
    "type": "bool"
  },
  "MiniMapUnitExp": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 54,
    "defaultValue": 0.25,
    "type": "float"
  },
  "MiniMapUnitSize": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 50,
    "defaultValue": 2.5,
    "minimumValue": 0,
    "type": "float"
  },
  "MinimizeOnFocusLoss": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 48,
    "description": "When set to 1 minimize Window if it loses key focus when in fullscreen mode.",
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 1,
    "type": "int"
  },
  "MouseDragBoxCommandThreshold": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 68,
    "description": "Distance in pixels which the mouse must be dragged to trigger a rectangular area command.",
    "defaultValue": 16,
    "type": "int"
  },
  "MouseDragCircleCommandThreshold": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 67,
    "description": "Distance in pixels which the mouse must be dragged to trigger a circular area command.",
    "defaultValue": 4,
    "type": "int"
  },
  "MouseDragFrontCommandThreshold": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 69,
    "description": "Distance in pixels which the mouse must be dragged to trigger a formation front command.",
    "defaultValue": 30,
    "type": "int"
  },
  "MouseDragScrollThreshold": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 65,
    "defaultValue": 0.3,
    "type": "float"
  },
  "MouseDragSelectionThreshold": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 66,
    "description": "Distance in pixels which the mouse must be dragged to trigger a selection box.",
    "defaultValue": 4,
    "type": "int"
  },
  "MouseRelativeModeWarp": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 56,
    "defaultValue": 1,
    "type": "bool"
  },
  "NetworkLossFactor": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 10,
    "defaultValue": 0,
    "minimumValue": 0,
    "maximumValue": 2,
    "type": "int"
  },
  "NetworkTimeout": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 19,
    "defaultValue": 120,
    "minimumValue": 0,
    "type": "int"
  },
  "NoHelperAIs": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/StartScriptGen.cpp",
    "declarationLine": 12,
    "defaultValue": 0,
    "type": "bool"
  },
  "OverheadEnabled": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/OverheadController.cpp",
    "declarationLine": 21,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "OverheadFOV": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/OverheadController.cpp",
    "declarationLine": 22,
    "defaultValue": 45,
    "type": "float"
  },
  "OverheadMaxHeightFactor": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/OverheadController.cpp",
    "declarationLine": 23,
    "description": "float multiplier for maximum overhead camera height",
    "defaultValue": 1,
    "type": "float"
  },
  "OverheadScrollSpeed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/OverheadController.cpp",
    "declarationLine": 19,
    "defaultValue": 10,
    "type": "int"
  },
  "OverheadTiltSpeed": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/OverheadController.cpp",
    "declarationLine": 20,
    "defaultValue": 1,
    "type": "float"
  },
  "PathingThreadCount": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Sim/Path/Default/PathEstimator.cpp",
    "declarationLine": 35,
    "defaultValue": 0,
    "minimumValue": 0,
    "safemodeValue": 1,
    "type": "int"
  },
  "PitchAdjust": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 29,
    "description": "Adjusts sound pitch proportional to [if set to 1, the square root of] game speed. Set to 2 for linear scaling.",
    "defaultValue": 0,
    "type": "int"
  },
  "ROAM": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFGroundDrawer.cpp",
    "declarationLine": 49,
    "description": "Use ROAM for terrain mesh rendering: 0 to disable, {1=VBO,2=DL,3=VA}-mode to enable.",
    "defaultValue": 1,
    "minimumValue": 0,
    "maximumValue": 3,
    "safemodeValue": 2,
    "type": "int"
  },
  "ReconnectTimeout": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 23,
    "defaultValue": 15,
    "minimumValue": 0,
    "type": "int"
  },
  "RotOverheadEnabled": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/RotOverheadController.cpp",
    "declarationLine": 15,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "RotOverheadFOV": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/RotOverheadController.cpp",
    "declarationLine": 16,
    "defaultValue": 45,
    "type": "float"
  },
  "RotOverheadMouseScale": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Camera/RotOverheadController.cpp",
    "declarationLine": 13,
    "defaultValue": 0.01,
    "type": "float"
  },
  "RotOverheadScrollSpeed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/RotOverheadController.cpp",
    "declarationLine": 14,
    "defaultValue": 10,
    "type": "int"
  },
  "RotateLogFiles": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/LogOutput.cpp",
    "declarationLine": 29,
    "description": "Rotate logfiles, old logfiles will be moved into the subfolder \"log\".",
    "defaultValue": 0,
    "type": "bool"
  },
  "SMFTexAniso": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFReadMap.cpp",
    "declarationLine": 35,
    "defaultValue": 4,
    "minimumValue": 0,
    "type": "float"
  },
  "SSMFTexAniso": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Map/SMF/SMFReadMap.cpp",
    "declarationLine": 36,
    "defaultValue": 4,
    "minimumValue": 0,
    "type": "float"
  },
  "ScreenshotCounter": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Screenshot.cpp",
    "declarationLine": 19,
    "defaultValue": 0,
    "type": "int"
  },
  "ScrollWheelSpeed": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MouseHandler.cpp",
    "declarationLine": 63,
    "defaultValue": 25,
    "minimumValue": -255,
    "maximumValue": 255,
    "type": "float"
  },
  "ServerLogDebugMessages": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 77,
    "defaultValue": 0,
    "type": "bool"
  },
  "ServerLogInfoMessages": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 76,
    "defaultValue": 0,
    "type": "bool"
  },
  "ServerRecordDemos": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 75,
    "defaultValue": 0,
    "dedicatedValue": 1,
    "type": "bool"
  },
  "ServerSleepTime": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 70,
    "description": "number of milliseconds to sleep per tick",
    "defaultValue": 5,
    "type": "int"
  },
  "SetCoreAffinity": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 99,
    "description": "Defines a bitmask indicating which CPU cores the main-thread should use.",
    "defaultValue": "0",
    "safemodeValue": "1",
    "type": "unsigned"
  },
  "ShadowMapSize": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/ShadowHandler.cpp",
    "declarationLine": 34,
    "description": "Sets the resolution of shadows. Higher numbers increase quality at the cost of performance.",
    "defaultValue": 2048,
    "minimumValue": 32,
    "type": "int"
  },
  "ShadowProjectionMode": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/ShadowHandler.cpp",
    "declarationLine": 35,
    "defaultValue": 1,
    "type": "int"
  },
  "Shadows": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/ShadowHandler.cpp",
    "declarationLine": 33,
    "description": "Sets whether shadows are rendered.\n-1:=forceoff, 0:=off, 1:=full, 2:=fast (skip terrain)",
    "defaultValue": 2,
    "minimumValue": -1,
    "safemodeValue": -1,
    "headlessValue": -1,
    "type": "int"
  },
  "ShowClock": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 134,
    "description": "Displays a clock on the top-right corner of the screen showing the elapsed time of the current game.",
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "ShowFPS": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 133,
    "description": "Displays current framerate.",
    "defaultValue": 0,
    "type": "bool"
  },
  "ShowPlayerInfo": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 136,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "int"
  },
  "ShowRezBars": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/FeatureDrawer.cpp",
    "declarationLine": 38,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "ShowSpeed": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 135,
    "description": "Displays current game speed.",
    "defaultValue": 0,
    "type": "bool"
  },
  "SimpleMiniMapColors": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/MiniMap.cpp",
    "declarationLine": 61,
    "defaultValue": 0,
    "type": "bool"
  },
  "SmallFontFile": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 24,
    "description": "Sets the font of Spring engine small text.",
    "defaultValue": "fonts/FreeSansBold.otf",
    "type": "std::string"
  },
  "SmallFontOutlineWeight": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 31,
    "description": "see FontOutlineWeight",
    "defaultValue": 10,
    "type": "float"
  },
  "SmallFontOutlineWidth": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 29,
    "description": "see FontOutlineWidth",
    "defaultValue": 2,
    "type": "int"
  },
  "SmallFontSize": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Fonts/glFont.cpp",
    "declarationLine": 27,
    "description": "Sets the font size (in pixels) of the engine GUIs and more.",
    "defaultValue": 14,
    "type": "int"
  },
  "Sound": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 22,
    "description": "Enables (OpenAL) or disables sound.",
    "defaultValue": 1,
    "type": "bool"
  },
  "SourcePort": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/Protocol/NetProtocol.cpp",
    "declarationLine": 21,
    "defaultValue": 0,
    "type": "int"
  },
  "SpeedControl": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 71,
    "description": "Sets how server adjusts speed according to player's load (CPU), 1: use average, 2: use highest",
    "defaultValue": 1,
    "minimumValue": 1,
    "maximumValue": 2,
    "type": "int"
  },
  "SplashScreenDir": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 107,
    "defaultValue": ".",
    "type": "std::string"
  },
  "SpringData": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/FileSystem/DataDirLocater.cpp",
    "declarationLine": 34,
    "description": "List of additional data-directories, separated by ';' on Windows and ':' on other OSs",
    "readOnly": 1,
    "defaultValue": "",
    "type": "std::string"
  },
  "SpringDataRoot": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/FileSystem/DataDirLocater.cpp",
    "declarationLine": 39,
    "description": "Optional custom data-directory content root ('base', 'maps', ...) to scan for archives",
    "readOnly": 1,
    "defaultValue": "",
    "type": "std::string"
  },
  "TCPAllowConnect": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/lib/luasocket/src/restrictions.cpp",
    "declarationLine": 24,
    "readOnly": 1,
    "defaultValue": "*",
    "type": "std::string"
  },
  "TCPAllowListen": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/lib/luasocket/src/restrictions.cpp",
    "declarationLine": 25,
    "readOnly": 1,
    "defaultValue": "*",
    "type": "std::string"
  },
  "TeamHighlight": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 53,
    "defaultValue": 1,
    "minimumValue": 0,
    "maximumValue": 2,
    "type": "int"
  },
  "TeamNanoSpray": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 46,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "TextureMemPoolSize": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 100,
    "defaultValue": "256",
    "minimumValue": "1",
    "type": "unsigned"
  },
  "TooltipGeometry": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/TooltipConsole.cpp",
    "declarationLine": 28,
    "defaultValue": "0.0 0.0 0.41 0.1",
    "type": "std::string"
  },
  "TooltipOutlineFont": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/UI/TooltipConsole.cpp",
    "declarationLine": 29,
    "defaultValue": 1,
    "headlessValue": 0,
    "type": "bool"
  },
  "TreeRadius": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/ITreeDrawer.cpp",
    "declarationLine": 21,
    "defaultValue": 1408,
    "minimumValue": 0,
    "headlessValue": 0,
    "type": "int"
  },
  "UDPAllowConnect": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/lib/luasocket/src/restrictions.cpp",
    "declarationLine": 26,
    "readOnly": 1,
    "defaultValue": "",
    "type": "std::string"
  },
  "UDPAllowListen": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/lib/luasocket/src/restrictions.cpp",
    "declarationLine": 27,
    "readOnly": 1,
    "defaultValue": "*",
    "type": "std::string"
  },
  "UDPConnectionLogDebugMessages": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Net/UDPConnection.cpp",
    "declarationLine": 20,
    "defaultValue": 0,
    "type": "bool"
  },
  "UnitIconDist": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/UnitDrawer.cpp",
    "declarationLine": 54,
    "defaultValue": 200,
    "headlessValue": 0,
    "type": "int"
  },
  "UnitLodDist": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/UnitDrawer.cpp",
    "declarationLine": 53,
    "defaultValue": 1000,
    "headlessValue": 0,
    "type": "int"
  },
  "UnitTransparency": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/UnitDrawer.cpp",
    "declarationLine": 55,
    "defaultValue": 0.7,
    "type": "float"
  },
  "UseDistToGroundForIcons": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Game/Camera/CameraController.cpp",
    "declarationLine": 11,
    "defaultValue": 0.95,
    "type": "float"
  },
  "UseEFX": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 24,
    "defaultValue": 1,
    "safemodeValue": 0,
    "type": "bool"
  },
  "UseFontConfigLib": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 103,
    "description": "Whether the system fontconfig library (if present and enabled at compile-time) should be used for handling fonts.",
    "defaultValue": 0,
    "type": "bool"
  },
  "UseHighResTimer": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 102,
    "description": "On Windows, sets whether Spring will use low- or high-resolution timer functions for tasks like graphical interpolation between game frames.",
    "defaultValue": 0,
    "type": "bool"
  },
  "UseLuaMemPools": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 101,
    "description": "Whether Lua VM memory allocations are made from pools.",
    "defaultValue": 1,
    "type": "bool"
  },
  "UseNetMessageSmoothingBuffer": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 58,
    "defaultValue": 1,
    "type": "bool"
  },
  "UsePBO": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GL/VBO.cpp",
    "declarationLine": 18,
    "defaultValue": 1,
    "safemodeValue": 0,
    "headlessValue": 0,
    "type": "bool"
  },
  "UseSDLAudio": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 25,
    "defaultValue": 0,
    "safemodeValue": 0,
    "type": "bool"
  },
  "UseShaderCache": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/Shaders/Shader.cpp",
    "declarationLine": 37,
    "description": "If already compiled shaders should be shared via a cache, reducing compiles of already compiled shaders.",
    "defaultValue": 1,
    "type": "bool"
  },
  "UseVBO": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GL/VBO.cpp",
    "declarationLine": 17,
    "defaultValue": 1,
    "safemodeValue": 0,
    "type": "bool"
  },
  "VFSCacheArchiveFiles": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/GlobalConfig.cpp",
    "declarationLine": 61,
    "defaultValue": 1,
    "type": "bool"
  },
  "VSync": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/VerticalSync.cpp",
    "declarationLine": 19,
    "description": "Synchronize buffer swaps with vertical blanking interval. Modes are -N (adaptive), +N (standard), or 0 (disabled).",
    "defaultValue": 0,
    "minimumValue": -6,
    "maximumValue": 6,
    "type": "int"
  },
  "Water": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/Env/IWater.cpp",
    "declarationLine": 24,
    "description": "Defines the type of water rendering. Can be set in game. Options are: 0 = Basic water, 1 = Reflective water, 2 = Reflective and Refractive water, 3 = Dynamic water, 4 = Bumpmapped water",
    "defaultValue": 1,
    "minimumValue": 0,
    "maximumValue": 4,
    "safemodeValue": 0,
    "headlessValue": 0,
    "type": "int"
  },
  "WhiteListAdditionalPlayers": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Net/GameServer.cpp",
    "declarationLine": 74,
    "defaultValue": 1,
    "type": "bool"
  },
  "WindowBorderless": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 51,
    "description": "When set and Fullscreen is 0, will put the game in Borderless Window mode, also known as Windowed Fullscreen. When using this, it is generally best to also set WindowPosX and WindowPosY to 0",
    "defaultValue": 0,
    "type": "bool"
  },
  "WindowPosX": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 58,
    "description": "Sets the horizontal position of the game window, if Fullscreen is 0. When WindowBorderless is set, this should usually be 0.",
    "defaultValue": 32,
    "type": "int"
  },
  "WindowPosY": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 59,
    "description": "Sets the vertical position of the game window, if Fullscreen is 0. When WindowBorderless is set, this should usually be 0.",
    "defaultValue": 32,
    "type": "int"
  },
  "WindowedEdgeMove": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Game/Game.cpp",
    "declarationLine": 130,
    "description": "Sets whether moving the mouse cursor to the screen edge will move the camera across the map.",
    "defaultValue": 1,
    "type": "bool"
  },
  "WorkerThreadCount": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Threading/ThreadPool.cpp",
    "declarationLine": 42,
    "description": "Number of workers (including the main thread!) used by ThreadPool.",
    "defaultValue": -1,
    "minimumValue": -1,
    "safemodeValue": 0,
    "type": "int"
  },
  "XResolution": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 54,
    "description": "Sets the width of the game screen. If set to 0 Spring will autodetect the current resolution of your desktop.",
    "defaultValue": 0,
    "minimumValue": 0,
    "headlessValue": 8,
    "type": "int"
  },
  "XResolutionWindowed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 56,
    "description": "See XResolution, just for windowed.",
    "defaultValue": 0,
    "minimumValue": 0,
    "headlessValue": 8,
    "type": "int"
  },
  "YResolution": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 55,
    "description": "Sets the height of the game screen. If set to 0 Spring will autodetect the current resolution of your desktop.",
    "defaultValue": 0,
    "minimumValue": 0,
    "headlessValue": 8,
    "type": "int"
  },
  "YResolutionWindowed": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/Rendering/GlobalRendering.cpp",
    "declarationLine": 57,
    "description": "See YResolution, just for windowed.",
    "defaultValue": 0,
    "minimumValue": 0,
    "headlessValue": 8,
    "type": "int"
  },
  "address": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/Menu/SelectMenu.cpp",
    "declarationLine": 44,
    "description": "Last Ip/hostname used as direct connect in the menu.",
    "defaultValue": "",
    "type": "std::string"
  },
  "name": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/SpringApp.cpp",
    "declarationLine": 105,
    "description": "Sets your name in the game. Since this is overridden by lobbies with your lobby username when playing, it usually only comes up when viewing replays or starting the engine directly for testing purposes.",
    "defaultValue": "UnnamedPlayer",
    "type": "std::string"
  },
  "snd_airAbsorption": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 37,
    "defaultValue": 0.1,
    "type": "float"
  },
  "snd_device": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 39,
    "description": "Sets the used output device. See \"Available Devices\" section in infolog.txt.",
    "defaultValue": "",
    "type": "std::string"
  },
  "snd_volbattle": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 34,
    "description": "Volume for \"battle\" sound channel.",
    "defaultValue": 100,
    "minimumValue": 0,
    "maximumValue": 200,
    "type": "int"
  },
  "snd_volgeneral": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 32,
    "description": "Volume for \"general\" sound channel.",
    "defaultValue": 100,
    "minimumValue": 0,
    "maximumValue": 200,
    "type": "int"
  },
  "snd_volmaster": {
    "isEnabled":'default',"isCommon":"1","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 31,
    "description": "Master sound volume.",
    "defaultValue": 60,
    "minimumValue": 0,
    "maximumValue": 200,
    "type": "int"
  },
  "snd_volmusic": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 36,
    "description": "Volume for \"music\" sound channel.",
    "defaultValue": 100,
    "minimumValue": 0,
    "maximumValue": 200,
    "type": "int"
  },
  "snd_volui": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 35,
    "description": "Volume for \"ui\" sound channel.",
    "defaultValue": 100,
    "minimumValue": 0,
    "maximumValue": 200,
    "type": "int"
  },
  "snd_volunitreply": {
    "isEnabled":'default',"isCommon":"0","declarationFile": "../../rts/System/Sound/ISound.cpp",
    "declarationLine": 33,
    "description": "Volume for \"unit reply\" sound channel.",
    "defaultValue": 100,
    "minimumValue": 0,
    "maximumValue": 200,
    "type": "int"
  }
}
window.freunds=[]